### PR TITLE
Allow URL schema resolving with rustls

### LINKED ISSUE #353: Cross compilation doesn't work with 0.15.1 enabling `reqwest/native-tls` by default
Hello @Stranger6667 , enabling reqwest/native-tls  by default to fix #343 causes cross-compilation to fail as native-tls depends on openssl and cross no longer bundles openssl (https://github.com/cross-rs/cross/issues/229).

Would it be possible to have another feature to use rustls in addition to the current `resolve-http` feature, as cross compiles work with it, i.e.

`resolve-http-rustls = ["reqwest", "rustls"]`

### PR DESCRIPTION
**Pull request by jqnatividad**
Hi @Stranger6667,
I'm also using jsonschema-rs as a library, and needed to use `rustls` with URL schemas, as cross no longer bundles openssl which `native-tls` requires. 

As per the README, I explicitly enabled `reqwest` and `rustls` and disabled `native-tls` via `default-features = false` in my Cargo.toml file but I still got the compilation error.

```
jsonschema = { version = "0.15.1", features = [
    "resolve-file",
    "reqwest",
    "rustls"
], default-features = false }
```

```
Compiling jsonschema v0.15.1
error: the `reqwest` feature does not enable HTTP schema resolving anymore, use the `resolve-http` feature instead
  --> C:\Users\jsmith\.cargo\registry\src\github.com-1ecc6299db9ec823\jsonschema-0.15.1\src\resolver.rs:81:21
   |
81 | ...   compile_error!("the `reqwest` feature does not enable HTTP schema resolving anymore, use the `resolve-http` feature instead");
```

I had to tweak the conditional compilation directives to get it to work.

Fixes #353

### CODE REVIEW

**Comment by Stranger6667** [comment]
Hi @jqnatividad !

Thank you, and sorry for not getting back to you in #353! I overlooked it :(
